language: c

before_install:
   - sudo apt-get update
   - sudo apt-get install gcc-multilib # needed for dmd on travis
   - make DC=$DC download
   - case "$DC" in
       dmd)
         ;;
       gdc)
         export PATH=$PATH:$PWD/x86_64-gdcproject-linux-gnu/bin;
         ;;
       ldc2)
         export PATH=$PATH:$PWD/ldc2-0.13.0-linux-x86_64/bin;
         ;;
     esac

env:
   global:
     - secure: "OZT3w/6lZwFfScZ5eQbtqYYOJMD9PJzHxmxCBV1HQjuPIx/ktSxXb73CUiob5bFK/rWjRlKBO8Jl1n9IDXMXSju+N1gR7O+vRwKelAyTBWjfGXHJeHyQddrCSrMkJ7o+Amvd+2LLrdPYQbS5uarb6jmm1CLz3j1TF36a2Jrup2s="
   matrix:
     - DC="dmd" BUILD="release"
     - DC="dmd" BUILD="debug"
     - DC="gdc" BUILD="release"
     - DC="gdc" BUILD="debug"
     - DC="ldc2" BUILD="release"
     - DC="ldc2" BUILD="debug"

script:
   - make DC=$DC BUILD=$BUILD dtest tests
   - make DC=$DC BUILD=$BUILD clean
   - make DC=$DC BUILD=$BUILD
   - ./example || true
   - make DC=$DC BUILD=$BUILD docs

after_success:
   - git remote set-url origin "https://${GH_TOKEN}@github.com/jkm/dtest.git"
   - test $DC = dmd -a $BUILD = release && make deploy
